fix(timeline_links): except the -NEXT Master contacts
newmatik/eso-frappe pull request #90
Opened 2024-07-31 06:59 UTC by shielasabellita

**Asana:** https://app.asana.com/0/1203283251131831/1207895033520677/f

**Issue:** 
NEXT Master contacts are used to link email to particular Customer/Supplier. With this, if it is linked to multiple customers, any notification made from user will populate to the timeline of the linked customer or supplier which it should not because it is not relevant. 

**Fix:** 
Except the NEXT Master contact in adding timeline links whenever a notification to the customer/supplier is made.

2024-07-31 12:43 UTC, dottenbr requested changes
I don't like this solution. Just ignore all users with @newmatik.com or @eso-electronic.com addresses instead.

2024-08-01 05:10 UTC, shielasabellita commented
Noted on this, Dominik. Thank you for the review.

2024-08-01 09:55 UTC, shielasabellita commented
* Removed the next master keyword validation
* Add a condition to don't create a timeline links if the Reference Doctype and Contact link is not the same

2024-08-01 12:07 UTC, dottenbr reviewed
I don't completely understand the change but if this makes sense to everyone, wouldn't this be a good thing to have in Open Source so we don't have to maintain?

2024-08-01 12:26 UTC, shielasabellita commented
According to the [documention](https://docs.erpnext.com/docs/user/manual/en/linking-emails-to-document#1-email-aggregation-for-customer-and-supplier), emailing linking to Customer or Supplier and as well as Contact is used for Email Aggregation. But as per the submitted issue, it should not display to Timeline because some information are unrelated.

2024-08-01 13:22 UTC, shielasabellita commented
Pushed a new code that will just comment the function that creates a TImeline Links base from the Contact's dynamic links.

2024-08-02 08:05 UTC, shielasabellita commented
As per discussion, there are other information that should be shown Customer/Supplier timeline logs. E.g. made an email from Sales Invoice, since Sales Invoice has connection to Customer, then a timeline should be created in both Sales Invoice, Customer. As well as Contact. 

In this PR, this will not create a link to every connected dynamic link. Thus, closing this for rework.

2024-08-02 08:05 UTC, closed without merging